services:
  account-service:
    build: ./account-service
    ports:
      - "8080:8080"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_NAME: App
      DB_USER: postgres
      DB_PASSWORD: admin
    networks:
      - backend

  school-service:
    build: ./school-service
    ports:
      - "8081:8081"
    depends_on:
      - account-service
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_NAME: App
      DB_USER: postgres
      DB_PASSWORD: admin
    networks:
      - backend

  timetable-service:
    build: ./timetable-service
    ports:
      - "8082:8082"
    depends_on:
      - account-service
      - school-service
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_NAME: App
      DB_USER: postgres
      DB_PASSWORD: admin
    networks:
      - backend

  document-service:
    build: ./document-service
    ports:
      - "8083:8083"
    depends_on:
      - account-service
      - school-service
      - timetable-service
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_NAME: App
      DB_USER: postgres
      DB_PASSWORD: admin
    networks:
      - backend

networks:
  backend:
